name: Docker

on:
  workflow_run:
    workflows: [Git-Tag]
    types: [completed]

permissions:
  packages: write
  contents: read

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/tree-species-unmixing

jobs:
  push:
    name: Push image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: convert image name to lower case
        run: echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME_LC
      - name: Push image
        run: |
          # Fetch all tags
          git fetch --tags
          # Get the latest tag reachable from HEAD
          VERSION=$(git describe --tags --abbrev=0)
          echo VERSION=$VERSION
          echo DOCKER=$DOCKER_USER/$IMAGE_NAME:$VERSION
          docker tag $IMAGE_NAME_LC $IMAGE_NAME_LC:$VERSION
          docker push $IMAGE_NAME_LC:$VERSION
          # Also tag and push as latest
          docker tag $IMAGE_NAME_LC $IMAGE_NAME_LC:latest
          docker push $IMAGE_NAME_LC:latest