name: Git-Tag

permissions:
  contents: write

on:
  push:

jobs:
  tagging:
    name: Create and Push Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for tags
          persist-credentials: true
      - name: Set up git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE_TIME=$(date +'%Y%m%d%H%M%S')
          TAG_NAME="1.${DATE_TIME}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
